app = "dashforge"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "http"
  [[services.ports]]
    port = 80

[[services.health_checks]]
  grace_period = "10s"
  interval = "15s"
  restart_limit = 3